spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${METRICS_DB_HOST:localhost}:${METRICS_DB_PORT:5434}/${METRICS_DB_NAME:metricsdb}

  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    com.contentaggregation.metrics: DEBUG

